# Generated by Django 5.1.3 on 2024-11-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_causa_user_donacion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='nombre_donante',
        ),
    ]
